# Generated by Django 2.1.5 on 2019-03-24 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message_html',
            field=models.TextField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
